"""
discriminator.py
----------------
DCGAN Discriminator for the AI Crop Disease Image Generator.

Architecture overview:
  Input: 3 × 128 × 128 RGB image
      → Conv2d blocks (downsample 128→64→32→16→8→4)
      → Flatten
      → Linear → Sigmoid
  Output: scalar probability (real=1, fake=0)
"""

import torch
import torch.nn as nn


class Discriminator(nn.Module):
    """
    DCGAN Discriminator.

    Classifies whether an input image is REAL (from the dataset)
    or FAKE (generated by the Generator).  Uses LeakyReLU activations
    and BatchNorm as recommended in the DCGAN paper.
    """

    def __init__(self, feature_maps: int = 64):
        """
        Parameters
        ----------
        feature_maps : int  Base number of feature maps (channels).
        """
        super(Discriminator, self).__init__()

        # ------------------------------------------------------------------
        # Convolutional feature extractor
        #   Input: (B, 3, 128, 128)
        #   After each block the spatial size is halved by stride=2.
        # ------------------------------------------------------------------
        self.main = nn.Sequential(
            # Block 1: 128 → 64   (no BatchNorm on first layer per DCGAN paper)
            nn.Conv2d(3, feature_maps,
                      kernel_size=4, stride=2, padding=1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),

            # Block 2: 64 → 32
            nn.Conv2d(feature_maps, feature_maps * 2,
                      kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(feature_maps * 2),
            nn.LeakyReLU(0.2, inplace=True),

            # Block 3: 32 → 16
            nn.Conv2d(feature_maps * 2, feature_maps * 4,
                      kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(feature_maps * 4),
            nn.LeakyReLU(0.2, inplace=True),

            # Block 4: 16 → 8
            nn.Conv2d(feature_maps * 4, feature_maps * 8,
                      kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(feature_maps * 8),
            nn.LeakyReLU(0.2, inplace=True),

            # Block 5: 8 → 4
            nn.Conv2d(feature_maps * 8, feature_maps * 16,
                      kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(feature_maps * 16),
            nn.LeakyReLU(0.2, inplace=True),
        )

        # ------------------------------------------------------------------
        # Classification head
        #   Flatten 4×4 feature map → single probability score
        # ------------------------------------------------------------------
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(feature_maps * 16 * 4 * 4, 1),
            nn.Sigmoid(),   # Output: probability ∈ [0, 1]
        )

        # Weight initialization
        self._initialize_weights()

    # ------------------------------------------------------------------
    # Forward pass
    # ------------------------------------------------------------------
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Parameters
        ----------
        x : torch.Tensor  shape (batch_size, 3, 128, 128)

        Returns
        -------
        torch.Tensor  shape (batch_size, 1)  — real/fake probability
        """
        features = self.main(x)         # (B, feature_maps*16, 4, 4)
        out = self.classifier(features)  # (B, 1)
        return out

    # ------------------------------------------------------------------
    # Weight initialization
    # ------------------------------------------------------------------
    def _initialize_weights(self):
        """
        Initialize Conv and BatchNorm weights per DCGAN paper.
        """
        for module in self.modules():
            if isinstance(module, nn.Conv2d):
                nn.init.normal_(module.weight.data, 0.0, 0.02)
            elif isinstance(module, nn.BatchNorm2d):
                nn.init.normal_(module.weight.data, 1.0, 0.02)
                nn.init.constant_(module.bias.data, 0)


# ---------------------------------------------------------------------------
# Quick sanity check
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    disc = Discriminator()
    fake_images = torch.randn(4, 3, 128, 128)   # batch of 4 random images
    out = disc(fake_images)
    print(f"Discriminator output shape: {out.shape}")  # Expected: (4, 1)
    print(f"Value range: [{out.min():.4f}, {out.max():.4f}]")
